// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MediaManager.ArchivingRulesTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "CallDurationArchivingRule")]
    public partial class CallDurationArchivingRuleFeature : object, Xunit.IClassFixture<CallDurationArchivingRuleFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "CallDurationArchivingRule"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CallDurationArchivingRule.feature"
#line hidden
        
        public CallDurationArchivingRuleFeature(CallDurationArchivingRuleFeature.FixtureData fixtureData, MediaManager_ArchivingRulesTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "CallDurationArchivingRule", "The CallDurationArchivingRule feature focuses on managing archiving calls based o" +
                    "n call duration,\r\ncovering scenarios for applying the call duration archiving ru" +
                    "le\r\nand refreshing call duration when configuration changes.", ProgrammingLanguage.CSharp, new string[] {
                        "CallDurationArchivingRule"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Apply call duration archiving rule with correct call duration")]
        [Xunit.TraitAttribute("FeatureTitle", "CallDurationArchivingRule")]
        [Xunit.TraitAttribute("Description", "Apply call duration archiving rule with correct call duration")]
        [Xunit.TraitAttribute("Category", "ApplyCallDurationArchivingRule")]
        [Xunit.InlineDataAttribute(">=", "2700", "1", "2024-03-01T10:00:00", "2024-03-01T11:00:00", "1,2", new string[0])]
        [Xunit.InlineDataAttribute("<", "2700", "2", "2024-03-01T09:00:00", "2024-03-01T09:30:00", "", new string[0])]
        public virtual void ApplyCallDurationArchivingRuleWithCorrectCallDuration(string comparisonOperator, string callDuration, string callId, string callStartTime, string callEndTime, string expectedResult, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ApplyCallDurationArchivingRule"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ComparisonOperator", comparisonOperator);
            argumentsOfScenario.Add("CallDuration", callDuration);
            argumentsOfScenario.Add("CallId", callId);
            argumentsOfScenario.Add("CallStartTime", callStartTime);
            argumentsOfScenario.Add("CallEndTime", callEndTime);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Apply call duration archiving rule with correct call duration", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
 testRunner.Given(string.Format("the call duration archiving rule is initialized with сomparison operator {0} and " +
                            "call duration {1}", comparisonOperator, callDuration), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.And(string.Format("a call event with special CallId {0} and CallStartTime {1}, CallEndTime {2}", callId, callStartTime, callEndTime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.When("the call duration archiving rule is applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 testRunner.Then(string.Format("it should return expected result {0} set of recording ids", expectedResult), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Refresh call duration when configuration changes")]
        [Xunit.TraitAttribute("FeatureTitle", "CallDurationArchivingRule")]
        [Xunit.TraitAttribute("Description", "Refresh call duration when configuration changes")]
        [Xunit.TraitAttribute("Category", "RefreshDuration")]
        [Xunit.InlineDataAttribute("2700", "CallDurationRuleConfig changed. Refreshed CallDuration", new string[0])]
        [Xunit.InlineDataAttribute("7777", "CallDurationRuleConfig changed. Refreshed CallDuration", new string[0])]
        public virtual void RefreshCallDurationWhenConfigurationChanges(string updatedCallDuration, string expectedLogMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RefreshDuration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UpdatedCallDuration", updatedCallDuration);
            argumentsOfScenario.Add("ExpectedLogMessage", expectedLogMessage);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Refresh call duration when configuration changes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
 testRunner.Given("an initial call duration configuration", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
 testRunner.When(string.Format("the configuration changes to updated call duration {0}", updatedCallDuration), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.Then(string.Format("it should refresh call directions and log the change with message {0}", expectedLogMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CallDurationArchivingRuleFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CallDurationArchivingRuleFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
